import Head from "next/head";
import { NextPage } from "next";
import { useState } from "react";
import Model from "../components/Model";


const Home: NextPage = () => {
  
  const [showModal, setShowModal] = useState < boolean > (false); 

  return (
    <div className="flex min-h-screen flex-col items-center justify-center py-2">
      <Head>
        <title>Modal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div >
        
        <Model show={showModal} setShow={setShowModal} />
        <button type="button" className="text-white bg-gradient-to-br from-purple-600 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2" onClick={() => setShowModal(true)}>Show Modal</button>

        

      </div>
      
    </div>
  );
}

export default Home;